LinkTrackerBot first implementation. Create service, handler, util. C…
BuchnevDmitry/LinkTracker pull request #3
Opened 2024-02-14 18:26 UTC by BuchnevDmitry

…reate unit test

2024-02-18 15:43 UTC, SHvatov requested changes
@BuchnevDmitry привет! Меня зовут Сергей, и в этом семестре я буду проверять твои работы :) Если будут какие-то вопросы, можешь их смело задавать мне. Еще я создал небольшую группу в телеге для всяких анонсов, чисто для тех, кто в моей группе - https://t.me/+KoDhaQZiHokwNDcy.

Оставил пару комментариев, посмотри их, пожалуйста.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/Bot.java
> +public interface Bot extends AutoCloseable, UpdatesListener {
А точно нужен интерфейс? Предполагается наличие множества реализаций?

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/LinkTrackerBot.java
> +@Component public class LinkTrackerBot extends TelegramBot implements Bot {
Аннотации лучше держать над классом, а то их может стать очень много.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/LinkTrackerBot.java
> +        start();
Вот это я бы вынес либо в @PostConstruct, либо вообще в @EventListener. Хорошо, что в данном случае start - чисто проставление полей в базовом классе. А ведь могло быть что-то ресурсоемкое, что могло потенциально заблокировать поток, в котором инициализируются бины.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/impl/HelpCommand.java
> +        commandList.forEach(command -> commandText.append(command.command()).append(delimiter)
аппенд на аппенде и командой погоняет :)

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/impl/TrackCommand.java
> +            Handler handlerUrl = new StackOverflowHandler();
На каждый запрос мы будем создавать по новому хэндлеру. Не надо так, давай унесем это в конструктор. А еще лучше вообще в отдельный класс, который будет заодно байндить эти самые хэндлеры.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/link/GitHubHandler.java
> +public class GitHubHandler extends Handler {
Такое чувство, будто это можно как-то унифицировать и обобщить)

![image](https://github.com/BuchnevDmitry/LinkTracker/assets/15994914/1b936542-222f-4d11-964b-75d67649f971)

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/link/Handler.java
> +public abstract class Handler {
Стоит конкретизировать название. В мире существует множество хэндлеров.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/impl/UserMessageServiceImpl.java
> +            log.error(e.getMessage());
Думаю стоит объединить лог

2024-02-18 15:43 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/util/BotUtil.java
> +public final class BotUtil {
Тут Util, потом Util**S**. Стоит выбрать что-то одно и придерживаться его.

2024-02-18 15:43 UTC, SHvatov commented on bot/src/test/java/edu/java/bot/сommand/CommandTest.java
> +public class CommandTest {
На будущее - покрытие команд тестами стоит увеличить.

2024-02-18 17:09 UTC, BuchnevDmitry commented on bot/src/main/java/edu/java/bot/handler/link/GitHubHandler.java
> +public class GitHubHandler extends Handler {
Но ведь в будущем там будет координально разная обработка ссылок, когда будет база данных

2024-02-18 17:14 UTC, BuchnevDmitry commented on bot/src/main/java/edu/java/bot/Bot.java
> +public interface Bot extends AutoCloseable, UpdatesListener {
Просто так было в примере интерфейсов, которые нужно создать

2024-02-24 12:28 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/Bot.java
> +public interface Bot extends AutoCloseable, UpdatesListener {
Ок, но в целом есть достаточно распространенное в комьюнити мнение, что плодить интерфейсы почем зря - не камильфо. Это пустые абстракции, которые, зачастую, не особенно то и нужны.

2024-02-24 12:28 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/handler/link/GitHubHandler.java
> +public class GitHubHandler extends Handler {
Обсудили в телеге, что необязательно и живем мы здесь и сейчас.

2024-02-24 12:30 UTC, SHvatov approved these changes
@BuchnevDmitry 👍, можно мержить.

2024-02-24 14:22 UTC, merged